# Generated by Django 5.0.6 on 2024-07-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='last_login_time',
        ),
    ]
