# Generated by Django 5.0.6 on 2024-07-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=50)),
                ('security_code', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('numero_celular', models.CharField(max_length=10)),
                ('titular', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
