# Generated by Django 5.0.6 on 2024-07-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='security_code',
            field=models.CharField(max_length=3),
        ),
    ]
