# Generated by Django 5.0.6 on 2024-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directos', '0002_directo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='directo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
